[package]
name = "wikibot"
version = "0.1.0"
publish = false
authors = ["Noah Morton <noahmorton98@gmail.com>"]

[profile.release]
debug = false
opt-level = 3

[dependencies]
serenity = "0.3.0"
rand = "0.3.16"
json = "0.11.9"
atom_syndication = "0.5.4"
reqwest = "0.7.2"
chrono = "0.4.0"
