[package]
name = "wikibot"
version = "0.1.0"
publish = false
authors = ["[Redacted] <nope@gmail.com>"]

[dependencies]
serenity = "0.3.0"
rand = "0.3.16"
json = "0.11.9"
atom_syndication = "0.5.4"
reqwest = "0.7.2"
chrono = "0.4.0"
lazy_static = "0.2.8"
