[package]
name = "wikibot"
version = "0.1.0"
publish = false
authors = ["[Redacted] <nope@gmail.com>"]

[dependencies]
serenity = "0.3"
rand = "0.3"
json = "0.11"
atom_syndication = "0.5"
reqwest = "0.7"
chrono = "0.4"
lazy_static = "0.2"
